[package]
name = "compile-time"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
time = { version = "0.3.17", features = ["macros", "formatting"] }
once_cell = "1"
